runtime: python312

entrypoint: gunicorn -b :$PORT app:app


env_variables:
  FLASK_ENV: "production"
  SECRET_KEY: "change-this-in-production"
  GA_SKIP_CACHE: "True"


handlers:
  # -----------------------------
  # Static files (CSS, JS, images)
  # -----------------------------
  - url: /static
    static_dir: static
    http_headers:
      Cache-Control: "public, max-age=300"   # 5 minutes caching

  # -----------------------------
  # Everything else goes to Flask
  # -----------------------------
  - url: /.*
    script: auto
    
    